Zipline:
  speed: 1.0
  max_radius: -1.0
Ziplining:
  finizh_raduis: 0.5
Item:
  ZiplineRecipe:
    ItemShape:
      - ILI
    RecipeItem:
      - I: IRON_INGOT
      - L: LEAD
  DebugStickRecipe:
    ItemShape:
      - D
      - S
    RecipeItem:
      - D: DIAMOND
      - S: STICK
Language:
  lang: ja
